[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["npm install", "npx prisma generate", "npx tsc"]

[start]
cmd = "node dist/server.js"
